### PR TITLE
Add Communicability (first try )

### PR DESCRIPTION
**Pull request by VirtuOes**
Hello,

I've just submitted a pull request where I've added a number of items, translated somewhat hastily, from my internal sources. These sources include 4-5 tenders related to medical software.

The contributions are primarily mapped to the "Qualitätsanforderung/Benutzerfreundlichkeit/*" categories.

I would greatly appreciate any feedback regarding the structure and process of my submission. This will help me to provide more relevant and useful content for the project in the future.

Kind regards,
Philipp

### CODE REVIEW

**Review by gernotstarke — CHANGES_REQUESTED** [review]
thanx for your contribution - really appreciated!

* "tags" MUST be from the 8 "properties" shown on the homepage. Please change the three you mentioned to "usable", maybe add "suitable". Please use NO COMMA here (it's a bug in our current implementation)
* we STRONGLY differentiate between definitions of quality attributes ("qualities"), which have to refer to "official" sources like ISO, wikipedia, known-books or similar
* the (measurable) requirements are distinct files, located under the "requirements" directory under the appropriate letter in a subdirectory "_posts". Maybe you just copy/paste one of the existing files.
* requirements should be MEASURABLE and therefore have a precise metric.

**Comment by VirtuOes** [comment]
Hello,

Thank you very much for the helpful feedback and clear instructions; I truly appreciate it.

I will take some time to refine and improve the quality of my submissions based on your guidance.

Best regards,
Philipp

**Comment by gernotstarke** [comment]
@Philipp, anything I can do to support your contribution?

In case you need technical support, we can delegate this to @Per-Starke, who is eager to help out with Git, Markdown + Jekyll related issues. Just let us know, please!

**Comment by Per-Starke** [comment]
@VirtuOes Feel free to contact me / just write an issue and assign me to that If you, as Gernot said, need any help with Git, Markdown, Jekyll and so on, I' here to help :)

**Comment by gernotstarke** [comment]
@VirtuOes - any news or updates from your side?
We will change the sites' technology in the near future, and like to include your updates before July 15th,
if possible... thanx for your cooperation!

**Comment by gernotstarke** [comment]
Hi @VirtuOes - I will add communicability as a quality and likewise add some of your examples, quoting your contribution.
Afterwards I'll close this PR. Thanx a lot!

**Pull request closed without merging**
